version: '3.8'

services:
  # Temporal Server
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.22.0
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  # Temporal Web UI
  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:2.18.0
    networks:
      - temporal-network
    ports:
      - 8080:8080

  # PostgreSQL Database
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
    networks:
      - temporal-network
    ports:
      - 5432:5432
    volumes:
      - temporal_postgresql_data:/var/lib/postgresql/data

  # Redis for Agent State Caching (Optional)
  redis:
    container_name: temporal-redis
    image: redis:7-alpine
    networks:
      - temporal-network
    ports:
      - 6379:6379
    volumes:
      - temporal_redis_data:/data

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  temporal_postgresql_data:
  temporal_redis_data:

